### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by TheNeikos**

### CODE REVIEW

**Comment by TheNeikos** [comment]
@CafeMaid r+

**Comment by TheNeikos** [comment]
@CafeMaid r+

**Comment by TheNeikos** [comment]
@CafeMaid r+

**Comment by CafeMaid** [comment]
:scream: Internal error: no commit found for PR

**Comment by TheNeikos** [comment]
@CafeMaid r+

**Comment by CafeMaid** [comment]
:-1: [Build failed](https://travis-ci.org/TheNeikos/furry.cafe/builds/180820331)

**Comment by TheNeikos** [comment]
@CafeMaid retry

**Comment by TheNeikos** [comment]
@CafeMaid r- r+

**Comment by TheNeikos** [comment]
@CafeMaid r+

**Comment by CafeMaid** [comment]
:-1: [Build failed](https://travis-ci.org/TheNeikos/furry.cafe/builds/180821134)

**Comment by TheNeikos** [comment]
@CafeMaid r+

**Comment by CafeMaid** [comment]
:-1: [Build failed](https://travis-ci.org/TheNeikos/furry.cafe/builds/180821516)

**Comment by notriddle** [comment]
rust-lang/cargo#3340

**Comment by TheNeikos** [comment]
@CafeMaid r+

**Comment by CafeMaid** [comment]
:-1: [Build failed](https://travis-ci.org/TheNeikos/furry.cafe/builds/180822815)

**Comment by TheNeikos** [comment]
@CafeMaid r+

**Comment by TheNeikos** [comment]
@CafeMaid r+

**Comment by CafeMaid** [comment]
:-1: [Build failed](https://travis-ci.org/TheNeikos/furry.cafe/builds/180948276)

**Comment by TheNeikos** [comment]
@CafeMaid r+

**Comment by CafeMaid** [comment]
:+1: [Build succeeded](https://travis-ci.org/TheNeikos/furry.cafe/builds/180949176)

**Pull request merged**
